### ISSUE TITLE
karma crash haraka

### ISSUE THREAD

**Issue by tmechlinski** [haraka/haraka-plugin-karma#16]
Fresh installation Haraka + Karma crash when start.
Without Karma plugin Haraka starts OK.

service haraka start
loaded TLD files: 1=1534 2=6132 3=2170
loaded 8229 Public Suffixes
loglevel: LOGINFO
Starting up Haraka version 2.8.13
[INFO] [-] [core] Loading plugins
...
[INFO] [-] [core] Loading plugin: karma
[NOTICE] [-] [core] the haraka-plugin- prefix is not required in config/plugins
**_[CRIT] [-] [core] TypeError: Cannot read property 'notes' of undefined_**
[CRIT] [-] [core]     at Plugin.exports.register (/data/node_modules/haraka-plugin-karma/index.js:33:16)
[CRIT] [-] [core]     at Object.plugins._register_plugin (/usr/local/lib/node_modules/Haraka/plugins.js:373:12)
[CRIT] [-] [core]     at Object.plugins.load_plugin (/usr/local/lib/node_modules/Haraka/plugins.js:346:17)
[CRIT] [-] [core]     at /usr/local/lib/node_modules/Haraka/plugins.js:318:17
[CRIT] [-] [core]     at Array.forEach (native)
[CRIT] [-] [core]     at Object.plugins.load_plugins (/usr/local/lib/node_modules/Haraka/plugins.js:317:17)
[CRIT] [-] [core]     at Object.Server.createServer (/usr/local/lib/node_modules/Haraka/server.js:266:20)
[CRIT] [-] [core]     at Object.<anonymous> (/usr/local/lib/node_modules/Haraka/haraka.js:76:8)
[CRIT] [-] [core]     at Module._compile (module.js:571:32)
[CRIT] [-] [core]     at Object.Module._extensions..js (module.js:580:10)
[NOTICE] [-] [core] Shutting down

ENV:

FreeBSD 10.3-RELEASE-p18 FreeBSD 10.3-RELEASE-p18 #0: Tue Apr 11 10:31:00 UTC 2017
Haraka.js — Version: 2.8.13
node-7.8.0_1 V8 JavaScript for client and server (7.x)
haraka-plugin-karma@1.0.7

**Comment by msimerson** [comment]
This is due to @smfreegard 's self merged and untested changes in #9. I'm of the opinion that his changes here and in haraka/haraka-results#4 should be reverted until after the next release. Then they can be attempted with an integration test that assures they continue to work after his changes.

**Comment by msimerson** [comment]
This is now fixed. Please try again.

**Comment by tmechlinski** [comment]
Everything works.
