### ISSUE TITLE
Asn keys without expiration in Redis

### ISSUE THREAD

**Issue by DoobleD** [haraka/haraka-plugin-karma#60]
**System Info:**

Haraka | Haraka.js — Version: 3.0.3
 --- | :--- 
Node | v20.11.1
OS | Linux mail.postale.io 5.15.0-1038-aws #43~20.04.1-Ubuntu SMP Fri Jun 2 17:10:57 UTC 2023 x86_64 GNU/Linux
openssl | OpenSSL 1.1.1w  11 Sep 2023

**Describe the bug**

In my redis I see asn keys without expiration:

```
local:6379> hgetall as12876
1) "connections"
2) "2"
3) "bad"
4) "2"
local:6379> ttl as12876
(integer) -1
```

**Expected behavior**

I expected asn keys to have an expiration, as per the [config](https://github.com/haraka/haraka-plugin-karma/blob/15825ea3f97649d403b1d909c4cc3980cb7332e5/config/karma.ini#L12) and the [code](https://github.com/haraka/haraka-plugin-karma/blob/15825ea3f97649d403b1d909c4cc3980cb7332e5/index.js#L1033). I haven't defined the `expire_days` setting, so I assumed it'd be set to the default (60 days).

Or is this behavior normal? I'll admit I haven't read the entire plugin code.

**Comment by msimerson** [comment]
Yes, this is normal. My thinking was, ASN numbers are far less transient than IP addresses, which get moved from customer to customer, and occasionally from provider to provider. Network management is durable and tends not to change frequently, so why should the ASNs score?

**Comment by DoobleD** [comment]
Thank you @msimerson. Over time these records accumulate to a significant number, but I get the point. Thanks for explaining!
